- name: Backend setup
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs

    - name: Copy Backend Service File
      ansible.builtin.copy: 
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Add Application User
      ansible.builtin.user:
        name: expense

    - name: Clean Old Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Content
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download frontend code and Extract it 
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes 

    - name: Install NodeJs Dependencies
      ansible.builtin.shell: npm install
      args:
          chdir: /app

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql.vaishnavidevops.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

    - name: Start Backend Service
      ansible.bulitin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes
        