- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Placing Expense Config file in Nginx
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

 - name: Include App Prerequisites 
   ansible.builtin.import_role:
     name: common
     tasks_from: app_prereq
    
- name: Starting Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
   